on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: docker4k8.azurecr.io
        username: ${{ secrets.acr_docker4k8_username }}
        password: ${{ secrets.acr_docker4k8_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t docker4k8.azurecr.io/k8:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push docker4k8.azurecr.io/k8:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetes-dashboard | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetes-dashboard`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetes-dashboard
        container-registry-url: docker4k8.azurecr.io
        container-registry-username: ${{ secrets.acr_docker4k8_username }}
        container-registry-password: ${{ secrets.acr_docker4k8_password }}
        secret-name: k8dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernetes-dashboard
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          docker4k8.azurecr.io/k8:${{ github.sha }}
        imagepullsecrets: |
          k8dockerauth
